#!/bin/bash
cd /System/Library/Audio/UISounds/SiriBackup
cp ./jbl_begin.caf /System/Library/Audio/UISounds/jbl_begin.caf
cd /System/Library/Audio/UISounds/SiriBackup
cp ./jbl_confirm.caf /System/Library/Audio/UISounds/jbl_confirm.caf
cd /System/Library/Audio/UISounds/SiriBackup
cp ./jbl_cancel.caf /System/Library/Audio/UISounds/jbl_cancel.caf

echo “Restart!”
echo “Restart!”
echo “Restart!”
echo “Made by Captain Poprocks”

exit 0

